### ISSUE TITLE
Some examples does not work in PAKCS 3.5.2

### ISSUE THREAD

**Issue by hakank** [finnteegen/pflp#1]
Two of the examples does not work using PAKCS version 3.5.2:
- examples/Bayesian.curry
- examples/RandomStrings.curry

At first, PAKCS complains about `import Float`, and after commenting that line it complains about undefined functions. Here's the output from the Baysian.curry program:
```
Prelude> :load Bayesian.curry 
Compiling Curry program "Bayesian"...

Bayesian.curry:7:34-7:35 Error:
    `-.' is undefined
   | 
 7 | flip p = enum [True,False] [p, 1 -. p]
   |                                  ^^

Bayesian.curry:45:43-45:44 Error:
    `/.' is undefined
    | 
 45 | rainWhenGrassWet = grassCondProb [g_, r_] /. grassCondProb [g_]
    |                                           ^^

Bayesian.curry:48:48-48:49 Error:
    `/.' is undefined
    | 
 48 | sprinklerWhenGrassWet = grassCondProb [g_, s_] /. grassCondProb [g_]
    |                                                ^^
ERROR occurred during parsing!

```

Perhaps I've missed something here...

Here's my setting:
- Linux Ubuntu 20.05 
- PAKCS version "Version 3.5.2-b5 of 2023-05-31 (sicstus 4.8)"
- PFLP is installed with CPM version 3.1.0 (31/05/2023)

**Comment by finnteegen** [comment]
Hello and thanks for pointing out this issue. These errors were caused by changes in the libraries as part of the addition of type classes to Curry. For example, arithmetic operators are now overloaded, which is why the `Float` library usually is no longer needed. I just updated the examples so they should work again. In the process, I also fixed another problem in `SecretSanta.curry`.
